version: '3.3'

services:
  wp_gatsbydev:
    depends_on:
      - wp_gatsbydev_db
    image: wordpress:latest
    volumes:
    - type: bind
      source: ./wp-content
      target: /var/www/html/wp-content
    ports:
      - "${WP_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wp_gatsbydev_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

  wp_gatsbydev_db:
    image: mysql:5.7
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - wp_gatsbydev_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wp_gatsbydev_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - /sessions
    links:
      - wp_gatsbydev_db:db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password

volumes:
    wp_gatsbydev_data: